### PR TITLE
AuraUI brand Logo disappears when the user selects the system theme issue has been fixed 

### PR DESCRIPTION
**Pull request by gaurangkeluskar22**
**PR will fix this prod bug https://github.com/Shubham0850/auraui/issues/13**

### CODE REVIEW

**Comment by Shubham0850** [comment]
Thanks for the PR @gaurangkeluskar22 , When you fix any issue can you please attach screen-shot or video of the issue after fix ? It will be easier for us to review your PR.

**Review by Shubham0850 — APPROVED** [review]
LGTM 🎉

**Comment by gaurangkeluskar22** [comment]
Hi @Shubham0850 , PFB the working solution video for the bug.

[](https://github.com/user-attachments/assets/42a1a56b-1a36-493a-b7a2-915d1a0e9070)

**Comment by Shubham0850** [comment]
Thanks for the video @gaurangkeluskar22

**Pull request merged**
